Create decorator to read in multiple files with pattern
koaning/clumper pull request #49
Opened 2020-09-06 11:55 UTC by samarpan-rai

2020-09-10 00:58 UTC, samukweku commented
Quiet On this function. Looks good and expanded my knowledge of decorators

2020-09-13 07:40 UTC, koaning commented on tests/test_decorator/test_multifile.py
> +    assert len(reader) == (copies) * len(writer)
These three tests are doing *nearly* the same thing. Might we be able to parametrize them? 

If you have something like; 

```
[(Clumper.read_csv, "tests/data/monopoly.csv"), (Clumper.read_jsonl, "tests/data/cards.jsonl"), ...])
```

Then you might be able to generalize this.

2020-09-13 07:41 UTC, koaning commented on tests/test_decorator/test_multifile.py
> +    assert len(reader) == (copies) * len(writer)
`(copies)` -> `copies`

2020-09-13 07:44 UTC, koaning requested changes
I have a minor request on the tests. There's some redundant characters. Other than that ... it looks good! I'll need to find some time to play with this locally but from looking at it -> looks great! 

@samarpan-rai @samukweku thanks!

2020-09-13 08:45 UTC, koaning commented
I'm reminded of something else. We need to add this feature to the docstrings!

2020-09-14 07:09 UTC, samarpan-rai commented
@koaning thank you for all the feedbacks. Should the docstring be a separate PR? I think adding documentation after merge would be neater but it's upto you. I can easily add documentation in the same PR.

2020-09-14 09:06 UTC, koaning commented
Docstring in a separate PR is fine.

2020-09-14 09:10 UTC, koaning commented
@samarpan-rai just to check, I can merge this?

2020-09-14 12:07 UTC, samarpan-rai commented
> @samarpan-rai just to check, I can merge this?

Yes.

> @samarpan-rai just to check, I can merge this?

Yes.

2020-09-14 12:33 UTC, merged